name: VulkanLearning CMake Workflow

on:
  push:
    branches: [ "gtact-workflows" ]
  pull_request:
    branches: [ "gtact-workflows" ]

env:
  BUILD_TYPE: Release
  CONAN_PRESET: conan-release

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup Environment
      shell: powershell
      run: |
        if (Test-Path -Path ${{github.workspace}}\build) {
            Remove-Item -Path ${{github.workspace}}\build -Recurse -Force
        }
        mkdir ${{github.workspace}}/build
        git submodule update --init --recursive --force

    - name: Configure Packages
      run: |
        python -m pip install conan
        conan profile detect --force
        conan install . --build=missing -pr=Profiles/Windows_x64_${{env.BUILD_TYPE}}
        conan build . -pr=Profiles/Windows_x64_${{env.BUILD_TYPE}}

    - name: Build Project
      run: |
        cmake --preset ${{env.CONAN_PRESET}}
        cmake --build --preset ${{env.CONAN_PRESET}}

    - name: Test Binaries
      working-directory: ${{github.workspace}}/build
      run: ctest -C ${{env.BUILD_TYPE}}
